name: Elixir CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.3']
        elixir: ['1.12.3', '1.14.5']
    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
  credo:
    runs-on: ubuntu-latest
    name: Credo OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.3', '26.2', '27.3']
        elixir: ['1.15.8', '1.16.3', '1.17.3', '1.18.3']
    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-credo
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run credo
      run: mix credo
  dialyzer:
    runs-on: ubuntu-latest
    name: Dialyzer OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.3']
        elixir: ['1.12.3']
    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-dialyzer
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run dialyzer
      run: mix dialyzer
